# Part 3: Lists and arrays in Numpy

## 3.1 Lists in python using numpy

#### Python uses libraries to load different functions 

Python uses numpy library to manipulate and create lists and arrays

Numpy library allows us to create arrays, and also all types of array manipulation such as access data and subarrays, and how to split, reshape and join arrays

In case you try to use a function, let's say create an array using the array function in numpy, and you haven't installed numpy previously, you will get the following error message

In [1]:
A1= np.array([1,4,2,5,3])

NameError: name 'np' is not defined

To start working with arrays, we need to import the **array function** from **numpy library**. Using the **import** command and  alias **np** to shorten the library name, we install that library

In [1]:
import numpy as np

The reason we write "import numpty **as np**" is so that referring to numpy functions can be shortened. For example, numpy.array() can be shortened to np.array(). 

We usually use aliases when importing Pandas libraries

Other packages and libraries you might use are **Pandas** for Dataframes, or **Matplotlib** for plottings and **Scikit-Learn** for Machine Learning analysis

Sometimes we might get an error message from python when some packages are not installed

**Working with Anaconda ensures most of the packages are installed** 

If we build our python models using Anaconda most of the required packages and libraries would be installed by default

There is a useful set of websites to help you install any packages in python using Anaconda

[Anaconda website section on how to install packages](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#:~:text=To%20install%20a%20package%20from%20Anaconda.org%3A%201%20In,to%20install%20the%20package.%20...%20More%20items...%20)
            

[Numpy](https://numpy.org/)

**Example of using the range function** 

The range  function is used to generate a sequence of numbers over time

In [39]:
x = range(1,20, 2)

In [40]:
type(x)

range

**This is an example of a loop in Python to access each element from the range object**

In [41]:
for n in x:
  print(n)

1
3
5
7
9
11
13
15
17
19


In [6]:
range(10)

range(0, 10)

***2. Let's now change this into a numpy list***

In [42]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

We can check whether this is a list 

In [43]:
type(L)

list

We can access individual list objects by indexing them 

**We can loop through the elements of the list L using a loop**

In [9]:
L=list(range(10))

The str() function converts the specified value into a string and you can use a **for** loop within the square brackets in this alternative way

In [44]:
L2 = [str(c) for c in L]

In [45]:
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [12]:
type(L2)

list

The list is a most versatile datatype available in Python which can be written as a list of comma-separated values (items) between square brackets. Important thing about a list is that items in a list need not be of the same type

In [13]:
L3 = str(L)

In [14]:
L3

'[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]'

In [15]:
type(L3)

str

The str() function of Python returns the string version of the object

In [47]:
thislist = ["apple","banana","cherry"]

In [48]:
thislist

['apple', 'banana', 'cherry']

In [49]:
type(thislist)

list

To access the first element we will type L[0]

In [50]:
L[0]

0

To access the third element we would type L[3]

In [51]:
L[1]

1

To access last element we would type L[-1]

In [52]:
L[-1]

9

We can get the data type of each of the elements by using type() function 

In [53]:
type(L[1])

int

A list in Python can contain both numeric and character elements. We can access character elements in a list in the same way we did with numeric ones earlier by using indexes

In [54]:
print(thislist[1])

banana


In [55]:
print(thislist[2])

cherry


**Important** In python the first element always starts with 0 not 1 

In [56]:
# In a python object first element is always 0 not 1 
print(thislist[0])

apple


**Important** In python the last element can be accessed by using - 1 

In [57]:
print(thislist[-1])

cherry


## Range of indexes

In [58]:
thislist = ["apple","banana","cherry","orange","kiwi","melon","mango"]

In [59]:
type(thislist)

list

**In a range of indexes the last item on the RIGHT of index[l:R] is EXCLUDED**

first item corresponds to apple



In a range of indexes the *last* item on the right side of the expression is **EXCLUDED**


Last item corresponds to Cherry :2 but it is excluded

In [28]:
print(thislist[0:2])

['apple', 'banana']


We list the second item int he range but it excluded when using a range 

In [60]:
print(thislist[:2])

['apple', 'banana']


In [30]:
print(thislist[2:])

['cherry', 'orange', 'kiwi', 'melon', 'mango']


This only happens to the index on the **RIGHT** side of the index notation, **not** on the LEFT side of it

In [61]:
print(thislist[1:5])

['banana', 'cherry', 'orange', 'kiwi']


In [62]:
## This will display items from "banana" to "kiwi"

In [63]:
print(thislist[0:7])

['apple', 'banana', 'cherry', 'orange', 'kiwi', 'melon', 'mango']


For the same reason mentioned above, if we want to display all elements from the list, we need to index one extra element as total number of items in the list 

**Specify negative indexes if you want to start the search from the end of the list**

In [64]:
print(thislist[-1])

mango


In [65]:
# This will revert the list 

**Further features using indexes**

This index will reverse the original list

In [67]:
print(thislist[::-1])

['mango', 'melon', 'kiwi', 'orange', 'cherry', 'banana', 'apple']


In [68]:
# This will print even items

In [69]:
print(thislist[::2])

['apple', 'cherry', 'kiwi', 'mango']


In [70]:
# This will print odd items

In [71]:
print(thislist[::1])

['apple', 'banana', 'cherry', 'orange', 'kiwi', 'melon', 'mango']


In [72]:
# This example returns the items from index -4 (included) to index -1 (excluded)
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]

In [73]:
print(thislist[-4:-1])

['orange', 'kiwi', 'melon']


In a range of indexes the *last* item on the right side of the expression is **EXCLUDED**

## 3.2 Arrays in Numpy

Arrays in python allows us to add operations to the data

We will use the ndarray object from NumPy package to perform these array operations


### 3.2.1 Creating arrays from lists 

In [74]:
List = list(range(10))

In [75]:
List

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [76]:
type(List)

list

Using numpy we can turn this list into an array

In [77]:
Ar1 = np.array([0,1,2,3,4,5,6,7,8,9])

In [78]:
Ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
type(Ar1)

numpy.ndarray

In [80]:
len(Ar1)

10

In [81]:
# This is  a standard list
L4 = ([1,4,2,5,3])

In [82]:
L4

[1, 4, 2, 5, 3]

In [83]:
type(L4)

list

We use the **array** function from numpy **np** library to turn a list into an array  

In [84]:
A1= np.array([1,4,2,5,3])

In [85]:
type(A1)

numpy.ndarray

In [86]:
A1

array([1, 4, 2, 5, 3])

### 3.2.2 Creating arrays from scratch

We can create specific arrays, like this one below populated with zeros, this is an example of one dimension array

In [87]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Then we can create multi-dimensional arrays by defining number of rows and cols

In [88]:
# Array filled in with ones
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

This is another example on how to create an array populated with 1 

In [60]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Populate an array with a specific value

In [89]:
# Array filled with number 3.14
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

We can also use arange function to creae adhoc list of numbers 

In [90]:
# Linear sequence 0,20 stepping by 2
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [91]:
# Five value evenly spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

We can also generate random numbers to populate an array

In [92]:
# Random values 0,1 in a 3x3 array
np.random.random((3,3))

array([[0.24610332, 0.90108737, 0.8511122 ],
       [0.13935333, 0.27446758, 0.87422817],
       [0.16671152, 0.56095386, 0.66042418]])

In [93]:
# Normal distributed, mean 0 sd 1 
np.random.normal(0,1,(3,3))

array([[ 1.12396521, -0.40484079,  0.63128288],
       [-0.08142314, -1.82538262, -0.71461307],
       [-0.51252594,  0.63474198, -0.48241968]])

In [94]:
# Random integers interval 0,10
np.random.randint(0,10,(3,3))

array([[9, 0, 5],
       [4, 3, 0],
       [9, 2, 6]])

We have a specific function to create Identity matrix

In linear algebra, the identity matrix (sometimes ambiguously called a unit matrix) of size n is the n × n square matrix with ones on the main diagonal and zeros elsewhere.

In [95]:
# Create a 3x3 Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 3.3 The Basics of NumPy Arrays

### 3.3.1 Attributes: Size, reshape , data types

When producing new calculations, by using random.seed() we ensure the reproductability of results when people run new calculations

In [96]:
np.random.seed(0)

In [97]:
# This is a one dimensional array
x1 = np.random.randint(10,size=6)

In [98]:
x1

array([5, 0, 3, 3, 7, 9])

In [99]:
X4 = np.random.randint(10,size=(3,2))

In [100]:
X4

array([[3, 5],
       [2, 4],
       [7, 6]])

In [101]:
print("x4 ndim:",X4.ndim)
print("x4 shape:",X4.shape)
print("x4 size:",X4.size)

x4 ndim: 2
x4 shape: (3, 2)
x4 size: 6


In [112]:
# This is a two dimensional array
x2 = np.random.randint(10,size=(3,4))

In [113]:
x2

array([[8, 8, 1, 6],
       [7, 7, 8, 1],
       [5, 9, 8, 9]])

In [114]:
print("x4 ndim:",x2.ndim)
print("x4 shape:",x2.shape)
print("x4 size:",x2.size)

x4 ndim: 2
x4 shape: (3, 4)
x4 size: 12


In [115]:
x3= np.random.randint(10,size=(3,4,5))

In [116]:
x3

array([[[4, 3, 0, 3, 5],
        [0, 2, 3, 8, 1],
        [3, 3, 3, 7, 0],
        [1, 9, 9, 0, 4]],

       [[7, 3, 2, 7, 2],
        [0, 0, 4, 5, 5],
        [6, 8, 4, 1, 4],
        [9, 8, 1, 1, 7]],

       [[9, 9, 3, 6, 7],
        [2, 0, 3, 5, 9],
        [4, 4, 6, 4, 4],
        [3, 4, 4, 8, 4]]])

In [117]:
print("x3 ndim:",x3.ndim)
print("x3 shape:",x3.shape)
print("x3 size:",x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


###  3.3.2 Array Indexing: Accessing Single Elements 

In [118]:
# Single Arrays

In [119]:
x1

array([5, 0, 3, 3, 7, 9])

In [120]:
x1[0]

5

In [121]:
x1[5]

9

In [122]:
x1[-1]

9

In [123]:
x1[2:5]

array([3, 3, 7])

In [124]:
x1[-2]

7

In [125]:
x1[::-1]

array([9, 7, 3, 3, 0, 5])

In [126]:
# Multidimensional arrays 
x2

array([[8, 8, 1, 6],
       [7, 7, 8, 1],
       [5, 9, 8, 9]])

In [128]:
x2[0,0]

8

In [129]:
x2[2,1]

9

In [130]:
x2[2,0:3]

array([5, 9, 8])

In [131]:
# This give us the four elements in the row 2 
x2[2,0:4]

array([5, 9, 8, 9])

###  3.3.3 Array Slicing: Accessing Subarrays 

In [132]:
# One dimensional arrays
x = np.arange(10)

In [133]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
x[:5]

array([0, 1, 2, 3, 4])

In [135]:
x[5:]

array([5, 6, 7, 8, 9])

In [136]:
x[4:7]

array([4, 5, 6])

In [137]:
# Display even elements
x[::2]

array([0, 2, 4, 6, 8])

In [138]:
# Display odd elements
x[1::2]

array([1, 3, 5, 7, 9])

In [139]:
# Reversed elements
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [140]:
# Reversed every element from 5
x[5::-1]

array([5, 4, 3, 2, 1, 0])

In [141]:
x[5::-2]

array([5, 3, 1])

In [142]:
x2

array([[8, 8, 1, 6],
       [7, 7, 8, 1],
       [5, 9, 8, 9]])

In [143]:
x2[:2,:3]

array([[8, 8, 1],
       [7, 7, 8]])

In [144]:
x2[:3,::2]

array([[8, 1],
       [7, 8],
       [5, 8]])

In [146]:
# Subarray dimensions can be reversed
x2[::-1,::-1]

array([[9, 8, 9, 5],
       [1, 8, 7, 7],
       [6, 1, 8, 8]])

In [147]:
# Access single rows or columns
# This will give you the first column (where the zero is, on the columns)
print(x2[:,0])

[8 7 5]


In [148]:
# This will give you the first row (where zero is, on the rows)
print(x2[0,:])

[8 8 1 6]


In [149]:
# Important: Subarrays return view. ALl the modifications we do the data they remain there
print(x2)

[[8 8 1 6]
 [7 7 8 1]
 [5 9 8 9]]


In [150]:
x2_sub = x2[:2,:2]

In [151]:
x2_sub

array([[8, 8],
       [7, 7]])

In [152]:
# Now we modify this subarray
x2_sub[0,0]=99
print(x2_sub)

[[99  8]
 [ 7  7]]


In [153]:
# The original array has changed
x2

array([[99,  8,  1,  6],
       [ 7,  7,  8,  1],
       [ 5,  9,  8,  9]])

#### 2.3.3.1 Creating copies of arrays

It is important as a standard practise, to create copies of datasets when using loops or functions, to avoid overwritting the content of arrays. 

In [154]:
# If we use .copy when creating sub-arrays, the original array is not touched

In [155]:
x2_sub_copy = x2[:2,:2].copy()

In [156]:
print(x2_sub_copy)

[[99  8]
 [ 7  7]]


In [157]:
# If we modify this subarray, the original array is not touched 
x2_sub_copy[0,0]=42

In [158]:
x2_sub_copy

array([[42,  8],
       [ 7,  7]])

In [159]:
# BY using a copy the original array is not touched

In [160]:
x2

array([[99,  8,  1,  6],
       [ 7,  7,  8,  1],
       [ 5,  9,  8,  9]])

###  3.3.4 Reshaping Arrays 

#### How to change the shape of an array, let's say from 1x9 to 3x3 

In [161]:
grid = np.arange(1,10)

In [162]:
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [163]:
# we can reshape it into a 3 by 3 array
grid_reshape = np.arange(1,10).reshape(3,3)

In [164]:
grid_reshape

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Important: The size of the initial array must match the size of the shaped array

In [165]:
print("grid size:",grid.size)

grid size: 9


In [166]:
print("grid_reshape size:",grid_reshape.size)

grid_reshape size: 9


#### Important: This is an example of the conversion of a one-dimensional array into a two-dimensional row or column matrix

In [167]:
x = np.array([1,2,3])

In [170]:
x

array([1, 2, 3])

In [171]:
x.shape

(3,)

We can create a row vector using the reshape function

In [176]:
#  column vector via  reshape
y= x.reshape((3,1))

In [177]:
y.shape

(3, 1)

In [173]:
x.ndim

1

In [178]:
x.shape


(3,)

Another option to create this row vector is to use np.newaxis function

In [179]:
#  column vector via  newaxis
x[np.newaxis,:]


array([[1, 2, 3]])

In [180]:
x

array([1, 2, 3])

### 3.3.5 Joining: Combining multiple arrays into one

### Concatenation of Arrays

In [181]:
x = np.array([1,2,3])

In [182]:
y = np.array([3,2,1])

In [183]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [137]:
# We can also concatenate several arrays at once

In [184]:
p = np.array([7,8,9])

In [185]:
print(np.concatenate([x,y,p]))

[1 2 3 3 2 1 7 8 9]


In [186]:
# You can concatenate along two different axis (2D Arrays)

In [187]:
narray = np.array([[2,4,5],
                  [6,2,1]])

In [188]:
# Concatenate along first axis (0)
np.concatenate([narray,narray])

array([[2, 4, 5],
       [6, 2, 1],
       [2, 4, 5],
       [6, 2, 1]])

In [189]:
# Concatenate along rows axis (1)
np.concatenate([narray,narray],axis=1)

array([[2, 4, 5, 2, 4, 5],
       [6, 2, 1, 6, 2, 1]])

####  Appending arrrays 

In some of our calculations, we would need to append arrays to modify the content of existing arrays, the append function from numpy library allows to do this data manipulation

In [190]:
Ap1 = np.random.randint(0,10,(3,3))

In [191]:
Ap2 = np.random.randint(10,20,(3,3))

In [192]:
Ap1

array([[3, 7, 5],
       [5, 0, 1],
       [5, 9, 3]])

In [193]:
Ap2

array([[10, 15, 10],
       [11, 12, 14],
       [12, 10, 13]])

In [194]:
APP = np.append(Ap1,Ap2)

In [149]:
APP

array([ 3,  7,  5,  5,  0,  1,  5,  9,  3, 10, 15, 10, 11, 12, 14, 12, 10,
       13])

####  Splitting  arrrays 

In [10]:
Sp1 = np.arange(16).reshape((4,4))

In [11]:
Sp1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
top, low = np.vsplit(Sp1,[2])

In [14]:
top

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [15]:
low

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Splitting arrays using array_split() function

### Friday 16th October 2020

These three cells below are a small reminder about how to join arrays in python

In [2]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


When joining two arrays, we can choose either joining them by rows (axis=1) or columns (axis=0)

* As a rule of thumb in python, when manipualating arrays: 
    - axis =1 alwyas refers to **Rows**
    - axis =0 always refers to **Columns**

In [4]:
arr3 = np.array([[1,2],[3,4]])
arr4 = np.array([[5,6],[7,8]])

In [7]:
arr3

array([[1, 2],
       [3, 4]])

In [8]:
arr4

array([[5, 6],
       [7, 8]])

Join arr3 and 4 by rows

In [12]:
arr_rows = np.concatenate((arr3,arr4),axis=1)

In [13]:
arr_rows

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

Then join arr3 and arr4 by columns

In [17]:
arr_cols = np.concatenate((arr3,arr4),axis=0)

In [18]:
arr_cols

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

We use array_split() function in Python as the reverse operation of joining

In [21]:
arr5 = np.array([3,6,7,3,1,8])

In [22]:
arr5

array([3, 6, 7, 3, 1, 8])

Now we split the array above into 3 parts

In [24]:
arr5spl = np.array_split(arr5,3)

In [25]:
print(arr5spl)

[array([3, 6]), array([7, 3]), array([1, 8])]


In [31]:
arr6 = np.arange(36).reshape((6,6))

In [32]:
arr6

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

We can split the above array into two arrays, the first one containig first column and the second one including the remain columns

This method will be extensively used when we conver **multiple regression** in Python, as python defines **target** and **feature** variables in a dataset in the form of **arrays** 

In [33]:
arr6_reg =  np.split(arr6,2)

In [34]:
arr6_reg

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]), array([[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In the example below, we want to split the array into two by columns 

In [36]:
arr6_regsp1 = np.split(arr6,2,axis=1)

In [37]:
arr6_regsp1

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20],
        [24, 25, 26],
        [30, 31, 32]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23],
        [27, 28, 29],
        [33, 34, 35]])]

Then we can try to split it by rows instead

In [39]:
arr6_regsp0 = np.split(arr6,2,axis=0)

In [40]:
arr6_regsp0

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]), array([[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [ ]:
https://towardsdatascience.com/numpy-array-cookbook-generating-and-manipulating-arrays-in-python-2195c3988b09

1.1 Hsplit horizontally split arrays into subarrays

In [41]:
Myarray = np.vsplit(arr6,2)

In [42]:
Myarray

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]), array([[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

1.2 Split above array to select just **first column** and save it as **Target** array

Remember the initial array we created at the start of this workbook

In [51]:
arr6

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

This method will be extensively used when we conver **multiple regression** in Python, as python defines **target** and **feature** variables in a dataset in the form of **arrays** 

1.2.1 Split above array to select just **first column** and save it as **Target** array

In [52]:
Target = arr6[:,0]

In [53]:
Target

array([ 0,  6, 12, 18, 24, 30])

1.2.2 Split arr6 to select rest of columns as **features** array

In [55]:
Features = arr6[:,1:6]

In [56]:
Features

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35]])

We can then use this **target** and **features** arrays in a standard **linear regression** model 

2. Example on how to use those features in a *linear regression* model

In [57]:
from sklearn.linear_model import LinearRegression
linear_model_Train = LinearRegression()


### Target array

The target variable is the one we want to predict in a linear regression, is defined by convenion as **Y**. The target array is **one dimensional**. It may include continuous numerical values or discrete calss/labels. In this example we use **Numpy** to define it as a **numerical array**. 

In [65]:
Target

array([ 0,  6, 12, 18, 24, 30])

In [66]:
Y_train = Target

In [67]:
Y_train

array([ 0,  6, 12, 18, 24, 30])

### Features matrix

We idenfity the features of quantitative piece of information in a linear regression as features, and they are arranged in columns. By convention the **features array** is stored in a variable called **X**. In a multiple regression scenario, we will have several columns in the features matrix, each column for a different feature we want to account in our prediction. 

In [68]:
X_train = Features

In [69]:
X_train

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35]])

### Linear model applied on the Target dataset

Just as an example, we can demonstrate how we will aply the numpy split to create a basic linear regression model for the train data

In [71]:
# fit model
My_model = linear_model_Train.fit(X_train,Y_train)


In [72]:
My_model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)